// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

const FirebaseOptions currentPlatform = FirebaseOptions(
    apiKey: "AIzaSyD8KxF8HqSEkbYGR02viB-wwa2lxxqGS7Y",
    authDomain: "sheba-finder.firebaseapp.com",
    projectId: "sheba-finder",
    storageBucket: "sheba-finder.firebasestorage.app",
    messagingSenderId: "155438022368",
    appId: "1:155438022368:web:71fe9724c6c95163435a85",
    measurementId: "G-NG3YFHLRB8",
  // নিচের লাইনটা যোগ করুন
    databaseURL: "https://sheba-finder-default-rtdb.firebaseio.com",
);