// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8KxF8HqSEkbYGR02viB-wwa2lxxqGS7Y',
    appId: '1:155438022368:web:71fe9724c6c95163435a85',
    messagingSenderId: '155438022368',
    projectId: 'sheba-finder',
    authDomain: 'sheba-finder.firebaseapp.com',
    storageBucket: 'sheba-finder.firebasestorage.app',
    measurementId: 'G-NG3YFHLRB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXkyFHVSSS6Pf3NceVWThXmSSxzfdxdFU',
    appId: '1:155438022368:android:3bf555c34505ea7b435a85',
    messagingSenderId: '155438022368',
    projectId: 'sheba-finder',
    storageBucket: 'sheba-finder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPLSy6LNle0f-b0bfaFtUIcfZsw2RWWNs',
    appId: '1:155438022368:ios:79fd48c88e2741fa435a85',
    messagingSenderId: '155438022368',
    projectId: 'sheba-finder',
    storageBucket: 'sheba-finder.firebasestorage.app',
    iosBundleId: 'com.example.shebafinderbdnew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPLSy6LNle0f-b0bfaFtUIcfZsw2RWWNs',
    appId: '1:155438022368:ios:79fd48c88e2741fa435a85',
    messagingSenderId: '155438022368',
    projectId: 'sheba-finder',
    storageBucket: 'sheba-finder.firebasestorage.app',
    iosBundleId: 'com.example.shebafinderbdnew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8KxF8HqSEkbYGR02viB-wwa2lxxqGS7Y',
    appId: '1:155438022368:web:95c342da736fcf6e435a85',
    messagingSenderId: '155438022368',
    projectId: 'sheba-finder',
    authDomain: 'sheba-finder.firebaseapp.com',
    storageBucket: 'sheba-finder.firebasestorage.app',
    measurementId: 'G-MFNPYKESNG',
  );
}
